export const SCHOOL = {
  name: 'Escuela Gabriela Mistral',
  shortName: 'Escuela GM',
  rbd: '6691-5',
  rut: '65145906-0',
  address: 'General Urrutia N° 763',
  phone: '+56 9 9643 2865',
  whatsapp: '+56996432865',
  email: 'EscuelaGM@gmail.com',
  city: 'Nueva Imperial',
  region: 'Región de La Araucanía',
  director: 'Alejandro Montes Riquelme',
  sostenedor: 'Corporación Educacional GM',
  foundedYear: 1980,
  socialMedia: {
    facebook: 'https://www.facebook.com/p/Escuela-Gabriela-Mistral-61550080885667/',
    instagram: 'https://www.instagram.com/escuela_gm/',
    youtube: '',
  },
} as const
